# Generated by Django 3.2.13 on 2022-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0002_klientas_ivykdytas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientas',
            name='ivykdytas',
            field=models.BooleanField(default=False, verbose_name='ivykdytas'),
        ),
    ]
