# Generated by Django 3.2.13 on 2022-05-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klientas_vardas', models.CharField(blank=True, max_length=124, null=True)),
                ('klientas_pavarde', models.CharField(blank=True, max_length=124, null=True)),
                ('klientas_email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(blank=True, default='marke', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metai', models.CharField(blank=True, default='metai', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelis', models.CharField(blank=True, default='modelis', max_length=20, null=True)),
                ('marke', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perziura.marke')),
            ],
        ),
        migrations.CreateModel(
            name='Spalva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spalva', models.CharField(blank=True, default='spalva', max_length=20, null=True)),
                ('modelis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='perziura.modelis')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='metai',
            name='modelis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='perziura.modelis'),
        ),
        migrations.AddField(
            model_name='klientas',
            name='marke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perziura.marke'),
        ),
        migrations.AddField(
            model_name='klientas',
            name='metai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perziura.metai'),
        ),
        migrations.AddField(
            model_name='klientas',
            name='modelis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perziura.modelis'),
        ),
        migrations.AddField(
            model_name='klientas',
            name='spalva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perziura.spalva'),
        ),
    ]
