# Generated by Django 3.2.13 on 2022-05-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0002_klientas_marke_metai_modelis_spalva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientas',
            name='klientas_pavarde',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='klientas',
            name='klientas_vardas',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='marke',
            name='marke',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metai',
            name='metai',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelis',
            name='modelis',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spalva',
            name='spalva',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
