# Generated by Django 3.2.13 on 2022-05-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0003_auto_20220510_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marke',
            name='marke',
            field=models.CharField(blank=True, default='marke', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metai',
            name='metai',
            field=models.CharField(blank=True, default='metai', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelis',
            name='modelis',
            field=models.CharField(blank=True, default='modelis', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spalva',
            name='spalva',
            field=models.CharField(blank=True, default='spalva', max_length=20, null=True),
        ),
    ]
