# Generated by Django 4.0.3 on 2022-04-30 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Marke',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='modelis',
            name='marke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perziura.marke'),
        ),
        migrations.AddField(
            model_name='klientas',
            name='marke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perziura.marke'),
        ),
        migrations.AddField(
            model_name='klientas',
            name='modelis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perziura.modelis'),
        ),
    ]
