# Generated by Django 4.0.3 on 2022-04-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0002_alter_marke_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marke',
            name='orders',
        ),
        migrations.AddField(
            model_name='marke',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='marke', to='perziura.order'),
        ),
    ]
