# Generated by Django 4.0.3 on 2022-05-02 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0002_klientas_modelis_remove_person_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=10, verbose_name='vardas')),
                ('pavarde', models.CharField(max_length=20, verbose_name='pavarde')),
                ('gimimo_data', models.CharField(max_length=20, verbose_name='gimimo data')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Uzsakymas',
                'verbose_name_plural': 'Uzsakymai',
            },
        ),
        migrations.CreateModel(
            name='Metai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobilio_pagaminimo_metai', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='automobilio pagaminimo metai')),
                ('modeliai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='metai', to='perziura.modelis')),
            ],
            options={
                'verbose_name': 'Metai',
                'verbose_name_plural': 'Metai',
            },
        ),
    ]
