# Generated by Django 4.0.3 on 2022-05-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0003_order_metai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marke',
            options={'verbose_name': 'Marke', 'verbose_name_plural': 'Markes'},
        ),
        migrations.AlterModelOptions(
            name='modelis',
            options={'verbose_name': 'Modelis', 'verbose_name_plural': 'Modeliai'},
        ),
        migrations.RenameField(
            model_name='klientas',
            old_name='name',
            new_name='klientas',
        ),
        migrations.RenameField(
            model_name='metai',
            old_name='automobilio_pagaminimo_metai',
            new_name='metai',
        ),
        migrations.RemoveField(
            model_name='marke',
            name='name',
        ),
        migrations.RemoveField(
            model_name='modelis',
            name='name',
        ),
        migrations.AddField(
            model_name='marke',
            name='marke',
            field=models.CharField(blank=True, default='pass', max_length=20, null=True, verbose_name='automobilio marke'),
        ),
        migrations.AddField(
            model_name='marke',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='marke', to='perziura.order'),
        ),
        migrations.AddField(
            model_name='modelis',
            name='modelis',
            field=models.CharField(blank=True, default='pass', max_length=20, null=True, verbose_name='automobilio modelis'),
        ),
        migrations.AlterField(
            model_name='modelis',
            name='marke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelis', to='perziura.marke'),
        ),
    ]
