# Generated by Django 4.0.3 on 2022-05-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0004_alter_marke_options_alter_modelis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marke',
            name='orders',
        ),
    ]
