# Generated by Django 4.0.3 on 2022-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0005_remove_marke_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klientas',
            name='klientas',
        ),
        migrations.AddField(
            model_name='klientas',
            name='klientas_pavarde',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='klientas',
            name='klientas_vardas',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='marke',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='marke', to='perziura.order'),
        ),
    ]
