# Generated by Django 4.0.3 on 2022-05-05 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0007_remove_order_gimimo_data_klientas_klientas_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spalva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spalva', models.CharField(blank=True, max_length=124, null=True)),
                ('modeliai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spalva', to='perziura.modelis')),
            ],
            options={
                'verbose_name': 'Spalva',
                'verbose_name_plural': 'Spalva',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='gimimo_data',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='metai',
            name='metai',
            field=models.DateField(blank=True, default=datetime.date.today, max_length=20, null=True, verbose_name='automobilio pagaminimo metai'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pavarde',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='pavarde'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vardas',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='vardas'),
        ),
        migrations.DeleteModel(
            name='Klientas',
        ),
    ]
