# Generated by Django 4.0.3 on 2022-05-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0009_alter_metai_modeliai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metai',
            options={'verbose_name': 'Metai', 'verbose_name_plural': 'Metais'},
        ),
        migrations.AlterField(
            model_name='metai',
            name='metai',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='automobilio pagaminimo metai'),
        ),
        migrations.AlterField(
            model_name='spalva',
            name='modeliai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spalva', to='perziura.modelis'),
        ),
    ]
