# Generated by Django 4.0.3 on 2022-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0012_alter_metai_metai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metai',
            name='metai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
