# Generated by Django 4.0.3 on 2022-05-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0013_alter_metai_metai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marke',
            name='orders',
        ),
        migrations.AddField(
            model_name='marke',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marke', to='perziura.order'),
        ),
    ]
