# Generated by Django 4.0.3 on 2022-05-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0014_remove_marke_orders_marke_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spalva',
            name='modeliai',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='spalva', to='perziura.modelis'),
        ),
    ]
