# Generated by Django 4.0.3 on 2022-05-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0015_alter_spalva_modeliai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klientas_vardas', models.CharField(max_length=124, null=True)),
                ('klientas_pavarde', models.CharField(max_length=124, null=True)),
                ('klientas_email', models.CharField(blank=True, max_length=30, null=True)),
                ('metai', models.CharField(blank=True, max_length=15, null=True)),
                ('spalva', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spalva',
            name='modeliai',
        ),
        migrations.AlterModelOptions(
            name='marke',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modelis',
            options={},
        ),
        migrations.RemoveField(
            model_name='marke',
            name='orders',
        ),
        migrations.AlterField(
            model_name='marke',
            name='marke',
            field=models.CharField(blank=True, default='mark', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modelis',
            name='marke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perziura.marke'),
        ),
        migrations.AlterField(
            model_name='modelis',
            name='modelis',
            field=models.CharField(blank=True, default='mod', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Metai',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Spalva',
        ),
        migrations.AddField(
            model_name='klientas',
            name='marke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perziura.marke'),
        ),
        migrations.AddField(
            model_name='klientas',
            name='modelis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perziura.modelis'),
        ),
    ]
