# Generated by Django 4.0.3 on 2022-05-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0016_klientas_remove_spalva_modeliai_alter_marke_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientas',
            name='modelis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perziura.modelis'),
        ),
        migrations.AlterField(
            model_name='modelis',
            name='modelis',
            field=models.CharField(blank=True, default='pass', max_length=20, null=True, verbose_name='automobilio modelis'),
        ),
    ]
