# Generated by Django 4.0.3 on 2022-05-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perziura', '0021_alter_metai_metai_alter_spalva_spalva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metai',
            name='modelis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='perziura.modelis'),
        ),
        migrations.AlterField(
            model_name='spalva',
            name='modelis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='perziura.modelis'),
        ),
    ]
